name: Build Boston Kernel
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: lss4/KernelSU_Action_pstar@Lineage_pstar
        with:
          kernel_url: 'https://github.com/MotorolaMobilityLLC/kernel-msm'
          kernel_branch: 'master'
          config: 'vendor/boston_defconfig'
          arch: 'arm64'
          ksu: true
          ksu_tag: 'main'
          boot_img_url: 'https://filebin.net/cebns0iwysbn1ug8'